const ROUTER_URL = {
  HOME: "/",
  ABOUT: `/about`,
  CONTACT: `/contact`,
  MENU: `/menu`,
  MEMBER: `/member`,
  FRANCHISE: `/franchise`,

  CLIENT: `/client`,
  CLIENT_ROUTER: {
    PRODUCT_DETAIL: `/client/product/:productId`,
    CLIENT_ORDER: `/client/order`,
    HISTORY: `/client/history`,
    CART: `/client/cart`,
    CHECKOUT: `/client/checkout`,
    PAYMENT_STATUS: "/client/payment-status/:success",
    CLIENT_ORDER_DETAIL: `/client/order/:orderId`,
    LOGIN: `/client/login`,
    REGISTER: `/client/register`,
    PROFILE: `/client/profile`,
    FORGOT_PASSWORD: `/client/forgot-password`,
    VERIFY: `/client/verify`,
    VERIFY_TOKEN: `/client/verify/:token`,
    VERIFY_CUSTOMER_EMAIL: `/verify-customer-email/:token`,
    LOYALTY: `/client/loyalty`,
  },

  ADMIN: `/admin`,
  ADMIN_ROUTER: {
    ADMIN_DASHBOARD: `/admin/dashboard`,
    ADMIN_MENU: `/admin/menu`,
    ADMIN_CATEGORY: `/admin/category`,
    ADMIN_CATEGORY_FRANCHISE: `/admin/category-franchise`,
    ADMIN_CUSTOMER: `/admin/customer`,
    ADMIN_FRANCHISE: `/admin/franchise`,
    ADMIN_INVENTORY: `/admin/inventory`,
    ADMIN_SHIFT_ASSIGNMENT: `/admin/shift-assignment`,
    ADMIN_LOYALTY: `/admin/loyalty`,
    ADMIN_ORDER: `/admin/order`,
    ADMIN_PAYMENT: `/admin/payment`,
    ADMIN_VOUCHER: `/admin/voucher`,
    ADMIN_PRODUCT: `/admin/product`,
    ADMIN_USER: `/admin/user`,
    ADMIN_SETTINGS: `/admin/settings`,
    ADMIN_PROFILE: `/admin/profile`,
    ADMIN_LOGOUT: `/admin/logout`,
    ADMIN_LOGIN: `/admin/login`,
    ADMIN_SELECT_CONTEXT: `/admin/select-context`,
    FORGOT_PASSWORD: `/admin/forgot-password`,
    REQUEST_NEW_PASSWORD: `/admin/request-new-password`,
    VERIFY_TOKEN: "/admin/verify",
    VERIFY_EMAIL: "/verify-email/:token",
    ADMIN_CART: `/admin/cart`,
  },
};

export default ROUTER_URL;
