export const SESSION_STORAGE = {
  ACCESS_TOKEN: "ACCESS_TOKEN",
  RESET_TOKEN: "RESET_TOKEN",
  ACCOUNT_CMS: "ACCOUNT_CMS",
  ADMIN_CONTEXT_REQUIRED: "ADMIN_CONTEXT_REQUIRED",
  FRANCHISE_ID: "FRANCHISE_ID",
} as const;

export type SessionStorageKey =
  (typeof SESSION_STORAGE)[keyof typeof SESSION_STORAGE];