import { PERM, type PermissionCode } from "./rbac.permissions";

/**
 * RBAC tạm theo seed role hiện tại: ADMIN / MANAGER / STAFF
 * - ADMIN (GLOBAL): full quyền + franchise management
 * - MANAGER (FRANCHISE): full quyền trong franchise, nhưng KHÔNG có franchise management, users, payments
 * - STAFF (FRANCHISE): read-only
 */
export const ROLE_PERMISSIONS: Record<string, PermissionCode[]> = {
  ADMIN: [
    PERM.FRANCHISE_MGMT,
    PERM.PRODUCT_READ,
    PERM.PRODUCT_WRITE,
    PERM.PRODUCT_CATEGORY_READ,
    PERM.CATEGORY_READ,
    PERM.CATEGORY_WRITE,
    PERM.CUSTOMER_READ,
    PERM.CUSTOMER_WRITE,
    PERM.ORDER_READ,
    PERM.ORDER_WRITE,
    PERM.PAYMENT_READ,
    PERM.PAYMENT_WRITE,
    PERM.VOUCHER_READ,
    PERM.VOUCHER_WRITE,
    PERM.INVENTORY_READ,
    PERM.INVENTORY_UPDATE,
    PERM.INVENTORY_ALERT,
    PERM.SHIFT_ASSIGNMENT_READ,
    PERM.SHIFT_ASSIGNMENT_WRITE,
    PERM.LOYALTY_READ,
    PERM.LOYALTY_WRITE,
    PERM.USER_READ,
    PERM.USER_MANAGE,
    PERM.CATEGORY_FRANCHISE_READ,
    PERM.CATEGORY_FRANCHISE_WRITE,
    PERM.PRODUCT_FRANCHISE_READ,
    PERM.PRODUCT_FRANCHISE_WRITE,
    PERM.SHIFT_READ,
    PERM.SHIFT_WRITE,
    PERM.CART_READ,
    PERM.CART_WRITE,
    PERM.PROMOTION_READ,
    PERM.PROMOTION_WRITE,
  ],

  // ✅ MANAGER: chỉ franchise-level, KHÔNG còn product/category tổng
  MANAGER: [
    PERM.MENU_READ,
    PERM.MENU_WRITE,

    // ❌ REMOVE:
    // PERM.PRODUCT_READ
    // PERM.CATEGORY_READ

    // ✅ ONLY franchise
    PERM.PRODUCT_FRANCHISE_READ,
    PERM.PRODUCT_FRANCHISE_WRITE,
    PERM.CATEGORY_FRANCHISE_READ,
    PERM.CATEGORY_FRANCHISE_WRITE,
    PERM.PRODUCT_CATEGORY_READ,

    PERM.CUSTOMER_READ,
    PERM.CUSTOMER_WRITE,
    PERM.ORDER_READ,
    PERM.ORDER_WRITE,
    PERM.USER_READ,
    PERM.INVENTORY_READ,
    PERM.INVENTORY_UPDATE,
    PERM.SHIFT_READ,
    PERM.SHIFT_WRITE,
    PERM.SHIFT_ASSIGNMENT_READ,
    PERM.SHIFT_ASSIGNMENT_WRITE,
    PERM.CART_READ,
    PERM.CART_WRITE,
    PERM.PAYMENT_READ,
    PERM.PAYMENT_WRITE,
    PERM.VOUCHER_READ,
    PERM.VOUCHER_WRITE,
    PERM.INVENTORY_READ,
    PERM.INVENTORY_UPDATE,
    PERM.INVENTORY_ALERT,
    PERM.LOYALTY_READ,
    PERM.LOYALTY_WRITE,
    PERM.PROMOTION_READ,
    PERM.PROMOTION_WRITE,
  ],

  // ✅ STAFF: chỉ READ + đúng scope bạn yêu cầu
  STAFF: [
    PERM.PRODUCT_FRANCHISE_READ,
    PERM.CUSTOMER_READ,
    PERM.ORDER_READ,
    PERM.INVENTORY_READ,
    PERM.CART_READ,
    PERM.CART_WRITE,
    PERM.SHIFT_READ,
    PERM.SHIFT_WRITE,
  ],
};
